env:
  browser: true
  es6: true
  jquery: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: script
globals:
  Typewriter: true
  UIkit: true
rules:
  array-bracket-newline:
    - warn
    - consistent
  block-scoped-var:
    - error
  brace-style:
    - warn
  comma-dangle:
    - warn
    - only-multiline
  comma-spacing:
    - warn
  comma-style:
    - warn
  curly:
    - error
    - all
  dot-location:
    - warn
    - property
  eol-last:
    - warn
  eqeqeq:
    - error
  function-paren-newline:
    - warn
    - consistent
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  lines-around-comment:
    - warn
    - afterBlockComment: true
      allowArrayStart: true
      allowBlockStart: true
      allowClassStart: true
      allowObjectStart: true
      beforeBlockComment: true
  lines-between-class-members:
    - warn
  max-len:
    - warn
    - code: 120
      ignoreUrls: true
      ignoreRegExpLiterals: true
  multiline-comment-style:
    - warn
    - starred-block
  new-parens:
    - warn
  no-alert:
    - warn
  no-caller:
    - error
  no-case-declarations:
    - error
  no-catch-shadow:
    - error
  no-confusing-arrow:
    - warn
  no-else-return:
    - warn
  no-extra-bind:
    - warn
  no-extra-label:
    - warn
  no-floating-decimal:
    - warn
  no-invalid-this:
    - error
  no-lone-blocks:
    - warn
  no-lonely-if:
    - warn
  no-multi-spaces:
    - warn
  no-new:
    - error
  no-param-reassign:
    - warn
  no-plusplus:
    - warn
  no-return-assign:
    - warn
  no-return-await:
    - warn
  no-tabs:
    - warn
  no-ternary:
    - warn
  no-trailing-spaces:
    - warn
  no-undef-init:
    - warn
  no-unused-vars:
    - warn
  no-use-before-define:
    - error
  no-useless-call:
    - warn
  no-var:
    - error
  object-curly-newline:
    - warn
  operator-assignment:
    - warn
    - always
  prefer-arrow-callback:
    - warn
    - allowNamedFunctions: false
      allowUnboundThis: false
  prefer-const:
    - warn
  prefer-numeric-literals:
    - warn
  prefer-template:
    - warn
  quotes:
    - warn
    - double
  quote-props:
    - warn
  semi:
    - error
    - always
  semi-spacing:
    - warn
  semi-style:
    - warn
  sort-imports:
    - warn
  sort-vars:
    - warn
  space-infix-ops:
    - warn
  space-unary-ops:
    - warn
    - words: true
      nonwords: true
  spaced-comment:
    - warn
    - always
  strict:
    - error
    - global
  wrap-iife:
    - warn
    - inside
  yoda:
    - error
    - never
