build:
    image: docker
    tags: docker
    only:
        - master
    script:
        - scripts/deploy-ci.sh

lint:
    image: pythondiscord/django-site-ci:latest
    script:
        - pipenv install --system --dev
        - flake8
