build base image:
    image: docker:stable-git
    script:
        - sh scripts/deploy-ci.sh
    tags:
        - docker
    only:
        - master
        - django
        - django+add-gitlab-ci

lint:
    image: pythondiscord/django-site-ci:latest
    script:
        - pipenv install --system --dev
        - flake8
