image: python:3.6-alpine3.7

variables:
  PIPENV_VENV_IN_PROJECT: 1
  PIPENV_IGNORE_VIRTUALENVS: 1
  RABBITMQ_HOST: rabbit
  RETHINKDB_HOST: rethinkdb


before_script:
  - apk add --update tini
  - apk add --update git
  - apk add --update build-base
  - apk add --update gcc
  - apk add --update cmake
  - apk add --update autoconf
  - apk add --update automake
  - apk add --update libtool

stages:
  - test
  - build

test:
  stage: test
  services:
    - name: rabbitmq:3.7.5-alpine
      alias: rabbit

    - name: rethinkdb:2.3.6
      alias: rethinkdb

  cache:
    paths:
      - ".venv"

  script:
    - apk add --update ruby ruby-dev ruby-rdoc ruby-irb
    - pip install pipenv
    - pipenv sync --dev --three
    - gem install scss_lint
    - pipenv run lint
    - pipenv run lintscss
    - pipenv run python gunicorn_config.py
    - pipenv run test

build:
  services:
    - docker:dind

  stage: build
  script:
    - apk add docker curl
    - sh scripts/deploy.sh
