language: python
python:
  - "3.6"
 
install:
  - pip install -r requirements.txt
  - pip install -r requirements-ci.txt
script:
  - snekchek
after_success:
  "curl https://api.beardfist.com/pythondiscord -H \"token: $AUTODEPLOY_TOKEN\""