version: "3.6"
services:
  django:
    image: registry.gitlab.com/python-discord/projects/site/django:latest
    depends_on:
    - migrator
    - postgres
    - web
    environment:
      DATABASE_URL: postgres://pysite:@postgres/pysite
      DEBUG: "0"
      SECRET_KEY: suitable-for-development-only
    ports:
    - "127.0.0.1:4000:4000"

  migrator:
    image: registry.gitlab.com/python-discord/projects/site/django:latest
    command: python manage.py migrate
    depends_on:
    - postgres
    environment:
      DATABASE_URL: postgres://pysite:@postgres/pysite
      DEBUG: "0"
      SECRET_KEY: suitable-for-development-only

  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: pysite
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: pysite

  web:
      image: pythondiscord/nging
