# Usage:
#   Install: docker 18.03 or higher
#   install: docker-compose 1.21.1 or higher
#   run: docker-compose up -d
#   wait for the containers to be up
#   confirm their ports are listening on the following ports: 5672, 28015

version: '3'
services:
  pdrdb:
    hostname: "pdrdb"
    image: pythondiscord/db:latest
    volumes:
      - "rdb:/data"
    entrypoint: su-exec daemon:daemon rethinkdb -n pdrdb -d /data --bind 0.0.0.0 --server-tag default --http-port 28010 --driver-port 28015
    network_mode: "host"

volumes:
    rdb:
