[tool.poetry]
name = "pysite"
version = "0.1.0"
description = "Our community website, built on Django."
authors = ["Johannes Christ <jc@jchri.st>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.7"
django = "^2.1"
django-hosts = "^3.0"
django-environ = "^0.4.5"
psycopg2-binary = "^2.7"
djangorestframework = "^3.8"
djangorestframework-bulk = "^0.2.1"
gunicorn = "^19.9"

[tool.poetry.dev-dependencies]
flake8 = "^3.5"
flake8-bugbear = "^18.8"
flake8-bandit = "^1.0"
flake8-import-order = "^0.18.0"
flake8-tidy-imports = "^1.1"
flake8-string-format = "^0.2.3"
coverage = "^4.5"
pep8-naming = "^0.7.0"
mccabe = "^0.6.1"
